### ISSUE TITLE
x86 and x64 versions

### ISSUE THREAD

**Issue by Neustradamus** [FoxP/PNG-to-ICO#8] opened 2024-02-29 01:27 UTC
Dear @FoxP,

Can you add two versions?
- One for x86 machines
- One for x64 machines

Thanks in advance.

**Comment by FoxP** [comment] 2024-02-29 11:01
Hello,
The app is a bat / cmd script : there is no x86 / x64 meaning for this.
King regards

**Comment by Neustradamus** [comment] 2024-02-29 13:02
It is needed to edit the .nsi to permit the folder install folder choice and have by default the "Program Files" or "Program Files (x86)":
- https://github.com/FoxP/PNG-to-ICO/blob/master/png_to_ico.nsi

After, it is needed to create a new release build with 2 installers -> 1 x86 and 1 x64 .exe.
You can have one build more with userdata folder too.

**Comment by FoxP** [comment] 2024-05-02 18:01
Duplicate of https://github.com/FoxP/PNG-to-ICO/issues/7

**Closed by FoxP** 2024-05-02 18:01 UTC
